# Generated by Django 5.1.4 on 2024-12-18 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_profile_github_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
