# Generated by Django 5.1.4 on 2024-12-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_rename_pub_date_content_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date published '),
        ),
    ]
